name: Pages deployment
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          cd front
          chmod +x ./build.sh
          ./build.sh
        env:
          VITE_ENV: production
      # - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      #   run: |
      #     cd front
      #     npm ci
      #     npm run build
      #   env:
      #     VITE_ENV: production

      # - name: Deploy ğŸš€
      #   uses: s0/git-publish-subdir-action@develop
      #   env:
      #     REPO: self
      #     BRANCH: pages
      #     FOLDER: front/dist
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     MESSAGE: "Build: ({sha}) {msg}" 
          